baseurl = "https://jmelis.github.io/one-daily-snippet"
languageCode = "en-us"
title = "ONE Daily Snippet"
theme = "purehugo"

[params]
hideShareOptions = true
description = "compiled by Bobby Tables"
